#Mad_Libs_Game

print('Welcome to Mad Libs Game', end='')
input()
print('Rules :', end='')
input()
print('Just enter the details and keep pressing ENTER', end='')
input()
input('Press Enter to continue....')
adj1 = input('Enter an adjective : ')
adj2 = input('Enter an adjective : ')
bird = input('Enter type of bird : ')
room = input('Enter room in house : ')
vb1 = input('Enter verb in past tense : ')
vb2 = input('Enter a verb : ')
name = input('Enter relative name : ')
noun = input('Enter a noun : ')
bird = input('Enter type of bird : ')
liq = input('Enter a liquid : ')
ing = input('Enter verb ending in -ing : ')
body = input('Enter part of body in plural form : ')

print('It was a', adj1, ',cold November day.', end='')
input()
print('I woke up to the', adj2, 'smell of', bird, 'roasting in the', room, 'room downstairs.', end='')
input()
print('I', vb1, 'down the stairs to see if I could help', vb2, 'the dinner.', end='')
input()
print('"See if', name, 'needs a fresh', noun, '".', end='')
input()
print('So I carried a tray of glasses full of', liq, 'into the', ing, 'room.', end='')
input()
print("When I got there, I couldn't believe my", body, '!')
